### ISSUE TITLE
最近没有更新么？

### ISSUE THREAD

**Issue by joint-song** [ZenDay/TypeScipt-Deep-Dive-chinese-version#1]
如果不忙的话可以一起继续翻译这个么？看到[原著](https://github.com/basarat/typescript-book)还在继续更新内容，而且之前我翻译了一些之后看到你的已经弄了很多了，就没继续

**Comment by ZenDay** [comment]
最近事情比较多，所以没有更新，抱歉。如果你有兴趣的话，不妨我们可以继续一起翻译。
