### ISSUE TITLE
我组织了一批人翻译这本书，请问是否可以引用您已翻译的部分

### ISSUE THREAD

**Issue by virtoolswebplayer** [ZenDay/TypeScipt-Deep-Dive-chinese-version#2]
我组织了一批人(公司内部社区)翻译这本书，请问是否可以引用您已翻译的部分

**Comment by ZenDay** [comment]
完全没有问题。
这段时间以来我一直忙于各种事情没有把这本书翻译完全并且更新到最新状态，我自己也很是惭愧。看到有人能继续把这本书的翻译做下去我也很开心。
加油！
